<?php
// $Id$

/**
 * @file
 * Install, update and uninstall functions for the field content types module.
 */

/**
 * Implements hook_field_schema().
 */
function field_content_types_field_schema($field) {
  return array(
    'columns' => array(
      'value' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
      ),
    ),
    'indexes' => array(
      'value' => array('value'),
    ),
  );
}